# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Club Name', max_length=50)),
                ('secy_details', models.CharField(default='Secy Details', max_length=500)),
                ('up_events', models.CharField(default='Future Events', max_length=500)),
                ('about_us', models.CharField(default='About Us', max_length=500)),
                ('past_events', models.CharField(default='Past Events', max_length=500)),
                ('projects', models.CharField(default='Projects', max_length=500)),
                ('links', models.CharField(default='Links', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='CodingClub',
        ),
    ]
