# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-12 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_auto_20170310_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='achievements',
            field=models.CharField(default='Links', max_length=500),
        ),
        migrations.AddField(
            model_name='clubs',
            name='contact',
            field=models.CharField(default='Links', max_length=500),
        ),
        migrations.AddField(
            model_name='clubs',
            name='extra',
            field=models.CharField(default='Links', max_length=500),
        ),
    ]
