# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-12 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0010_auto_20170312_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Board Name', max_length=50)),
                ('chairman_details', models.CharField(blank=True, default='', max_length=500000)),
                ('chairman_pic', models.ImageField(default='pic_folder/no-img2.jpg', upload_to='pic_folder/')),
                ('gensec_details', models.CharField(blank=True, default='', max_length=500000)),
                ('gensec_pic', models.ImageField(default='pic_folder/no-img2.jpg', upload_to='pic_folder/')),
                ('eventManager_details', models.CharField(blank=True, default='', max_length=500000)),
                ('eventManager_pic', models.ImageField(default='pic_folder/no-img2.jpg', upload_to='pic_folder/')),
                ('announcements', models.CharField(blank=True, default='', max_length=500000)),
                ('about_us', models.CharField(blank=True, default='', max_length=500000)),
                ('extra', models.CharField(blank=True, default='', max_length=500000)),
                ('event1_name', models.CharField(blank=True, default='', max_length=500000)),
                ('event1_details', models.CharField(blank=True, default='', max_length=500000)),
                ('event2_name', models.CharField(blank=True, default='', max_length=500000)),
                ('event2_details', models.CharField(blank=True, default='', max_length=500000)),
                ('event3_name', models.CharField(blank=True, default='', max_length=500000)),
                ('event3_details', models.CharField(blank=True, default='', max_length=500000)),
                ('event4_name', models.CharField(blank=True, default='', max_length=500000)),
                ('event4_details', models.CharField(blank=True, default='', max_length=500000)),
                ('event5_name', models.CharField(blank=True, default='', max_length=500000)),
                ('event5_details', models.CharField(blank=True, default='', max_length=500000)),
                ('car_pic1', models.ImageField(default='pic_folder/no-img2.jpg', upload_to='pic_folder/')),
                ('car_pic2', models.ImageField(default='pic_folder/no-img2.jpg', upload_to='pic_folder/')),
                ('car_pic3', models.ImageField(default='pic_folder/no-img2.jpg', upload_to='pic_folder/')),
                ('car_pic4', models.ImageField(default='pic_folder/no-img2.jpg', upload_to='pic_folder/')),
            ],
        ),
        migrations.AlterField(
            model_name='clubs',
            name='car_pic1',
            field=models.ImageField(default='pic_folder/no-img2.jpg', upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='car_pic2',
            field=models.ImageField(default='pic_folder/no-img2.jpg', upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='car_pic3',
            field=models.ImageField(default='pic_folder/no-img2.jpg', upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='secy_pic',
            field=models.ImageField(default='pic_folder/no-img2.jpg', upload_to='pic_folder/'),
        ),
    ]
