# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0013_announcements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivements',
            name='Description',
            field=models.CharField(blank=True, default='Description here', max_length=10000),
        ),
        migrations.AlterField(
            model_name='achivements',
            name='Link',
            field=models.CharField(blank=True, default='Link here', max_length=100),
        ),
    ]
